import React, { useCallback, useRef, useState } from "react";
import { px } from "../dom/units";
import { Resizable } from "./shared/Resizable";
import { Scrollable } from "./shared/Scrollable";

export function GlobalNavigation() {
  const [width, setWidth] = useState(px(120));

  const onResize = (newWidth: string) => {
    setWidth(newWidth);
    console.log("on resize: ", newWidth);
  };

  return (
    <Resizable width={width} onResize={onResize}>
      <Scrollable>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
      </Scrollable>
    </Resizable>
  );
}
