import React from "react";
import { Resizable } from "./shared/Resizable";
import { Scrollable } from "./shared/Scrollable";

export function GlobalNavigation() {
  const onScroll = (scrollPos: number) => {
    console.log(scrollPos);
  };

  return (
    <Resizable>
      <Scrollable onScroll={onScroll}>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Here</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Is</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Some</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
        <div>Long</div>
      </Scrollable>
    </Resizable>
  );
}
