import React from "react";
import { Scrollable } from "./Scrollable";

export function GlobalNavigation() {
  return (
    <Scrollable>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Here</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Is</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Some</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
      <div>Long</div>
    </Scrollable>
  );
}
