#!/bin/sh

# Increment version?
echo "Increment version? (patch/minor/major)"
read INCREMENT

case $INCREMENT in
  patch)
    echo "PATCH"
    npm version patch
  ;;

  minor)
    echo "MINOR"
    npm version minor
  ;;

  major)
    echo "MAJOR"
    npm version major
  ;;

  *)
    echo "Sorry, invalid input. Goodbye."
    exit 1
esac

Build it
npm run-script publish

# Make the new output directory
VERSION=$(grep version package.json | awk -F \" '{print $4}')
mkdir  "out/v${VERSION}"

# Copy output to version specific directory
cd out

cp "deb/x64/marker_${VERSION}_amd64.deb" "v${VERSION}/marker.deb"
cp "rpm/x64/marker_${VERSION}_amd64.rpm" "v${VERSION}/marker.rpm"

echo "DONE!"