#!/bin/sh

# Handy-dandy little build script with the ability to update the package version
# prior to building. Will also copy out .rpm, and .deb files aftewards.

set -e

# Ensure it passes unit tests first
npm run test || echo 1

# Increment version?
echo "Increment version? (patch/minor/major)"
read INCREMENT

case $INCREMENT in
  patch)
    echo "PATCH"
    npm version patch
  ;;

  minor)
    echo "MINOR"
    npm version minor
  ;;

  major)
    echo "MAJOR"
    npm version major
  ;;

  *)
    echo "Sorry, invalid input. Goodbye."
    exit 1
esac

Build it
npm run-script publish || exit 1

# Make the new output directory
VERSION=$(grep version package.json | awk -F \" '{print $4}')
mkdir  "out/v${VERSION}"

# Copy output to version specific directory
cd out

mv "make/deb/x64/marker_${VERSION}_amd64.deb" "v${VERSION}/marker-v${VERSION}.deb"
mv "make/rpm/x64/marker-${VERSION}-1.x86_64.rpm" "v${VERSION}/marker-v${VERSION}.rpm"

echo "DONE!"